### ISSUE TITLE
burh i need help 

### ISSUE THREAD

**Issue by 50shine** [fin3ss3g0d/evilgophish#36]
i did everything you said still get 400 error
![Screenshot_2023-01-18_11_51_55](https://user-images.githubusercontent.com/105277058/213244646-89d7d319-89e1-418a-a068-76b6b02c4359.png)

**Comment by fin3ss3g0d** [comment]
Do I have to tell you what the errors mean or can you not read them for yourself? You're adding a phishlet that's not packaged with the original project and you're not including it in the `evilginx2/phishlets` folder before running `setup.sh`. Because you did this, the script did not handle setting up SSL certificates for that phishlet and `evilginx2` is trying to create them for you but is failing. Generate proper SSL certificates for the phishlet and place them in the appropriate directory. Read the `Prerequisites` section before submitting an issue, you should understand the underlying projects to this level before trying to setup and use this project. I'm going to close similar issues you open, you've opened three separate issues and are poisoning this issues section. I want real issues submitted and not your complaints about getting set up. You clearly don't know how to use `evilginx2` at a basic level, you should do more research on the tools involved before using this project.

**Comment by 50shine** [comment]
burh same error just help ik how to use evilginx2 fine works for me fine

**Comment by fin3ss3g0d** [comment]
I told you how to help. Generate proper SSL certificates, copy/paste them in the right folder, and restart evilginx2. This is a simple error and fix, I don't know what is so difficult to figure out?

**Comment by 50shine** [comment]
Do you have telegram because it gave me the same error when I use a default
phishlets

**Comment by 50shine** [comment]
so i have to Generate ssl for every phishlets even the default ones

**Comment by 50shine** [comment]
> I told you how to help. Generate proper SSL certificates, copy/paste them in the right folder, and restart evilginx2. This will fix the error. This is a simple error and fix, what are you not understanding?

so i have to Generate ssl for every phishlets even the default ones

**Comment by 50shine** [comment]
> I told you how to help. Generate proper SSL certificates, copy/paste them in the right folder, and restart evilginx2. This will fix the error. This is a simple error and fix, what are you not understanding?

 it gave me the same error when I use a default
phishlets

**Comment by 50shine** [comment]
> I told you how to help. Generate proper SSL certificates, copy/paste them in the right folder, and restart evilginx2. This will fix the error. This is a simple error and fix, what are you not understanding?

not really understanding wym dont have to that with evilgin2

**Comment by fin3ss3g0d** [comment]
I created `setup.sh` which tells you the command needed to generate the certificates and it automatically configures the project with them. If you want to know how to manually setup SSL certificates for evilginx2, refer to its README. I'm not teaching people how to create SSL certificates or how to use evilginx2, so if you continue asking I'm going to close or not reply. I created a `Prerequisites` section for this project, you should already understand how to do this before using this project.
