### ISSUE TITLE
phishing url returns 404 Not Found

### ISSUE THREAD

**Issue by cparonny** [fin3ss3g0d/evilgophish#61]
Phishing URL returning 404 instead of 200

## Current Behavior

I have a freshly installed evilgophish 
no tweak at all same response on other phishlets also

![image](https://user-images.githubusercontent.com/55528085/236627073-683a2ec3-204c-4e3e-be93-0abc6668ff04.png)

![image](https://user-images.githubusercontent.com/55528085/236627142-ccd406e6-26c2-4ba1-8d71-a420e873feb9.png)

here is apache access log: 
`"GET /test HTTP/1.1" 404 500 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"`

**Comment by fin3ss3g0d** [comment]
You are requesting port 80, your lure is on 443

**Comment by cparonny** [comment]
ok i was using cloudflare it was pulling data over port 80.

But when i set cloudflare ssl/tls mode to Full ( i mean tell cloudflare to pull over 443 )

it returns 521

![image](https://user-images.githubusercontent.com/55528085/236638561-491f724e-fd6f-4ebf-804e-a619447a22f1.png)

![image](https://user-images.githubusercontent.com/55528085/236638575-b2f893bb-f751-4391-ab34-bd439d9c069d.png)

**Comment by fin3ss3g0d** [comment]
I haven't provided instructions for this kind of set up and I'm not providing support for it. Since you have taken on this kind of set up and it's not provided within the default project, you should have enough knowledge and understanding in order to debug the errors you are receiving based on the technologies involved.
